/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Experiment,
    ExperimentFromJSON,
    ExperimentToJSON,
} from '../models';

export interface OptimizerRunRequest {
    experiment: Experiment;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Run optimizer with the specified parameters
     */
    async optimizerRunRaw(requestParameters: OptimizerRunRequest): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.experiment === null || requestParameters.experiment === undefined) {
            throw new runtime.RequiredError('experiment','Required parameter requestParameters.experiment was null or undefined when calling optimizerRun.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/optimizer`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExperimentToJSON(requestParameters.experiment),
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Run optimizer with the specified parameters
     */
    async optimizerRun(requestParameters: OptimizerRunRequest): Promise<string> {
        const response = await this.optimizerRunRaw(requestParameters);
        return await response.value();
    }

}
