/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface OptimizerRunRequest {
    params?: string;
    xi?: number;
    yi?: number;
    kappa?: number;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Run optimizer with the specified parameters
     */
    async optimizerRunRaw(requestParameters: OptimizerRunRequest): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters.params !== undefined) {
            queryParameters['params'] = requestParameters.params;
        }

        if (requestParameters.xi !== undefined) {
            queryParameters['Xi'] = requestParameters.xi;
        }

        if (requestParameters.yi !== undefined) {
            queryParameters['yi'] = requestParameters.yi;
        }

        if (requestParameters.kappa !== undefined) {
            queryParameters['kappa'] = requestParameters.kappa;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/optimizer`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Run optimizer with the specified parameters
     */
    async optimizerRun(requestParameters: OptimizerRunRequest): Promise<string> {
        const response = await this.optimizerRunRaw(requestParameters);
        return await response.value();
    }

}
