// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultResultModels
 */
export interface ResultResultModels {
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof ResultResultModels
     */
    expectedMinimum?: Array<Array<number>>;
    /**
     * 
     * @type {object}
     * @memberof ResultResultModels
     */
    extras?: object;
}

export function ResultResultModelsFromJSON(json: any): ResultResultModels {
    return ResultResultModelsFromJSONTyped(json, false);
}

export function ResultResultModelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultResultModels {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expectedMinimum': !exists(json, 'expected_minimum') ? undefined : json['expected_minimum'],
        'extras': !exists(json, 'extras') ? undefined : json['extras'],
    };
}

export function ResultResultModelsToJSON(value?: ResultResultModels | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expected_minimum': value.expectedMinimum,
        'extras': value.extras,
    };
}

