// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ResultPlots
 */
export interface ResultPlots {
  /**
   *
   * @type {string}
   * @memberof ResultPlots
   */
  id?: string
  /**
   * A base64 encoded png representation of the plot
   * @type {string}
   * @memberof ResultPlots
   */
  plot?: string
}

export function ResultPlotsFromJSON(json: any): ResultPlots {
  return ResultPlotsFromJSONTyped(json, false)
}

export function ResultPlotsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResultPlots {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    plot: !exists(json, 'plot') ? undefined : json['plot'],
  }
}

export function ResultPlotsToJSON(value?: ResultPlots | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    plot: value.plot,
  }
}
