/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ExperimentExtrasSelectedPointInner
 */
export interface ExperimentExtrasSelectedPointInner {}

/**
 * Check if a given object implements the ExperimentExtrasSelectedPointInner interface.
 */
export function instanceOfExperimentExtrasSelectedPointInner(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ExperimentExtrasSelectedPointInnerFromJSON(
  json: any
): ExperimentExtrasSelectedPointInner {
  return ExperimentExtrasSelectedPointInnerFromJSONTyped(json, false)
}

export function ExperimentExtrasSelectedPointInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ExperimentExtrasSelectedPointInner {
  return json
}

export function ExperimentExtrasSelectedPointInnerToJSON(
  value?: ExperimentExtrasSelectedPointInner | null
): any {
  return value
}
