/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * A plain JSON object that can contain arbitrary values
 * @export
 * @interface ExperimentExtras
 */
export interface ExperimentExtras {
  /**
   *
   * @type {string}
   * @memberof ExperimentExtras
   */
  objectivePars?: ExperimentExtrasObjectiveParsEnum
}

/**
 * @export
 */
export const ExperimentExtrasObjectiveParsEnum = {
  Result: 'result',
  ExpectedMinimum: 'expected_minimum',
} as const
export type ExperimentExtrasObjectiveParsEnum =
  (typeof ExperimentExtrasObjectiveParsEnum)[keyof typeof ExperimentExtrasObjectiveParsEnum]

/**
 * Check if a given object implements the ExperimentExtras interface.
 */
export function instanceOfExperimentExtras(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ExperimentExtrasFromJSON(json: any): ExperimentExtras {
  return ExperimentExtrasFromJSONTyped(json, false)
}

export function ExperimentExtrasFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ExperimentExtras {
  if (json === undefined || json === null) {
    return json
  }
  return {
    objectivePars: !exists(json, 'objectivePars')
      ? undefined
      : json['objectivePars'],
  }
}

export function ExperimentExtrasToJSON(value?: ExperimentExtras | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    objectivePars: value.objectivePars,
  }
}
