/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ExperimentDataInnerXiInner
 */
export interface ExperimentDataInnerXiInner {}

/**
 * Check if a given object implements the ExperimentDataInnerXiInner interface.
 */
export function instanceOfExperimentDataInnerXiInner(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ExperimentDataInnerXiInnerFromJSON(
  json: any
): ExperimentDataInnerXiInner {
  return ExperimentDataInnerXiInnerFromJSONTyped(json, false)
}

export function ExperimentDataInnerXiInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ExperimentDataInnerXiInner {
  return json
}

export function ExperimentDataInnerXiInnerToJSON(
  value?: ExperimentDataInnerXiInner | null
): any {
  return value
}
