/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ExperimentDataInnerXiInner } from './ExperimentDataInnerXiInner'
import {
  ExperimentDataInnerXiInnerFromJSON,
  ExperimentDataInnerXiInnerFromJSONTyped,
  ExperimentDataInnerXiInnerToJSON,
} from './ExperimentDataInnerXiInner'

/**
 *
 * @export
 * @interface ExperimentDataInner
 */
export interface ExperimentDataInner {
  /**
   *
   * @type {Array<ExperimentDataInnerXiInner>}
   * @memberof ExperimentDataInner
   */
  xi?: Array<ExperimentDataInnerXiInner>
  /**
   *
   * @type {Array<number>}
   * @memberof ExperimentDataInner
   */
  yi?: Array<number>
}

/**
 * Check if a given object implements the ExperimentDataInner interface.
 */
export function instanceOfExperimentDataInner(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ExperimentDataInnerFromJSON(json: any): ExperimentDataInner {
  return ExperimentDataInnerFromJSONTyped(json, false)
}

export function ExperimentDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ExperimentDataInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    xi: !exists(json, 'xi')
      ? undefined
      : (json['xi'] as Array<any>).map(ExperimentDataInnerXiInnerFromJSON),
    yi: !exists(json, 'yi') ? undefined : json['yi'],
  }
}

export function ExperimentDataInnerToJSON(
  value?: ExperimentDataInner | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    xi:
      value.xi === undefined
        ? undefined
        : (value.xi as Array<any>).map(ExperimentDataInnerXiInnerToJSON),
    yi: value.yi,
  }
}
