/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ResultPlotsInner
 */
export interface ResultPlotsInner {
  /**
   *
   * @type {string}
   * @memberof ResultPlotsInner
   */
  id?: string
  /**
   * A base64 encoded png representation of the plot
   * @type {string}
   * @memberof ResultPlotsInner
   */
  plot?: string
}

/**
 * Check if a given object implements the ResultPlotsInner interface.
 */
export function instanceOfResultPlotsInner(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ResultPlotsInnerFromJSON(json: any): ResultPlotsInner {
  return ResultPlotsInnerFromJSONTyped(json, false)
}

export function ResultPlotsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResultPlotsInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    plot: !exists(json, 'plot') ? undefined : json['plot'],
  }
}

export function ResultPlotsInnerToJSON(value?: ResultPlotsInner | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    plot: value.plot,
  }
}
