/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ResultResultModelsInner
 */
export interface ResultResultModelsInner {
  /**
   *
   * @type {Array<Array<number>>}
   * @memberof ResultResultModelsInner
   */
  expectedMinimum?: Array<Array<number>>
  /**
   *
   * @type {object}
   * @memberof ResultResultModelsInner
   */
  extras?: object
}

/**
 * Check if a given object implements the ResultResultModelsInner interface.
 */
export function instanceOfResultResultModelsInner(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ResultResultModelsInnerFromJSON(
  json: any
): ResultResultModelsInner {
  return ResultResultModelsInnerFromJSONTyped(json, false)
}

export function ResultResultModelsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResultResultModelsInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    expectedMinimum: !exists(json, 'expected_minimum')
      ? undefined
      : json['expected_minimum'],
    extras: !exists(json, 'extras') ? undefined : json['extras'],
  }
}

export function ResultResultModelsInnerToJSON(
  value?: ResultResultModelsInner | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    expected_minimum: value.expectedMinimum,
    extras: value.extras,
  }
}
