/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ResultResultExtras
 */
export interface ResultResultExtras {
  /**
   * True iff the server reused the pickled cache hint for this response.
   * @type {boolean}
   * @memberof ResultResultExtras
   */
  pickledUsed?: boolean
}

/**
 * Check if a given object implements the ResultResultExtras interface.
 */
export function instanceOfResultResultExtras(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ResultResultExtrasFromJSON(json: any): ResultResultExtras {
  return ResultResultExtrasFromJSONTyped(json, false)
}

export function ResultResultExtrasFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResultResultExtras {
  if (json === undefined || json === null) {
    return json
  }
  return {
    pickledUsed: !exists(json, 'pickledUsed') ? undefined : json['pickledUsed'],
  }
}

export function ResultResultExtrasToJSON(
  value?: ResultResultExtras | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    pickledUsed: value.pickledUsed,
  }
}
