/* tslint:disable */
/* eslint-disable */
/**
 * Process Optimizer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SpaceInner
 */
export interface SpaceInner {
  /**
   * Type of the dimension. Can be category, discrete or continuous
   * @type {string}
   * @memberof SpaceInner
   */
  type: SpaceInnerTypeEnum
  /**
   *
   * @type {string}
   * @memberof SpaceInner
   */
  name: string
  /**
   *
   * @type {number}
   * @memberof SpaceInner
   */
  from?: number
  /**
   *
   * @type {number}
   * @memberof SpaceInner
   */
  to?: number
  /**
   *
   * @type {Array<string>}
   * @memberof SpaceInner
   */
  categories?: Array<string>
}

/**
 * @export
 */
export const SpaceInnerTypeEnum = {
  Category: 'category',
  Discrete: 'discrete',
  Continuous: 'continuous',
} as const
export type SpaceInnerTypeEnum =
  (typeof SpaceInnerTypeEnum)[keyof typeof SpaceInnerTypeEnum]

/**
 * Check if a given object implements the SpaceInner interface.
 */
export function instanceOfSpaceInner(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'type' in value
  isInstance = isInstance && 'name' in value

  return isInstance
}

export function SpaceInnerFromJSON(json: any): SpaceInner {
  return SpaceInnerFromJSONTyped(json, false)
}

export function SpaceInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SpaceInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    type: json['type'],
    name: json['name'],
    from: !exists(json, 'from') ? undefined : json['from'],
    to: !exists(json, 'to') ? undefined : json['to'],
    categories: !exists(json, 'categories') ? undefined : json['categories'],
  }
}

export function SpaceInnerToJSON(value?: SpaceInner | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    type: value.type,
    name: value.name,
    from: value.from,
    to: value.to,
    categories: value.categories,
  }
}
